# https://github.com/CaiJimmy/hugo-theme-stack-starter/tree/master/config/_default
# https://stack.jimmycai.com/config/comments
# https://hugo.opendocs.io/zh-cn/getting-started/directory-structure/
# https://github.com/Oddyti/oddyti.github.io/blob/master/config.yaml

# Change baseurl before deploy
baseURL: 'https://yjwang01.github.io'
languageCode: zh-cn
title: "Yum's website"
paginate: 5
theme: 'hugo-theme-stack'
copyright: Yum

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

languages:
    en:
        languageName: English
        title: "Yum's website"
        weight: 1
        params:
            description: Example description
    zh-cn:
        languageName: 中文
        title: Yum 的记录站
        weight: 2
        params:
            description: 演示说明

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

permalinks:
    post: /post/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon: img/favicon.ico
    # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2024
        customText: 

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: "🌞"
        subtitle: Hello, world!
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        headingAnchor: false
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: giscus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client/props.html
        waline:
            serverURL: https://walinecomments-bhh3vo7i5-yjwang01s-projects.vercel.app
            lang: zh-CN
            visitor: false
            avatar:
            emoji:
                - https://unpkg.com/@waline/emojis@1.1.0/weibo/
                # - https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tieba
                # - https://cdn.jsdelivr.net/gh/walinejs/emojis/qq
                # - https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/alus
            requiredMeta:
                - name
                - email
            placeholder:
            locale:
                admin: Yum

        twikoo:
            envId:
            region:
            path:
            lang:
        
        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)
        
        giscus:
            repo: "yjwang01/Giscus"
            repoID: R_kgDOMV0jMQ
            category: "Announcements"
            categoryID: DIC_kwDOMV0jMc4Cgw4O
            mapping: pathname
            strict: 0
            lightTheme: "light"
            darkTheme: "transparent_dark"
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                limit: 10
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter

menu:
    main: []
        # - identifier: home
        #   name: Home
        #   url: /
        #   weight: -100
        #   params:
        #     icon: home

        # - identifier: about
        #   name: About
        #   url: /about
        #   weight: -90
        #   params:
        #     icon: user

        # - identifier: archives
        #   name: Archives
        #   url: /archives
        #   weight: -80
        #   params:
        #     icon: archives

        # - identifier: tags
        #   name: Tags
        #   url: /tags
        #   weight: -70
        #   params:
        #     icon: tag

        # - identifier: search
        #   name: Search
        #   url: /search
        #   weight: -60
        #   params:
        #     icon: search

        # - identifier: link
        #   name: Links
        #   url:  /link
        #   weight: -50
        #   params:
        #     icon: link

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/yjwang01
          weight: -100
          params:
            icon: github

        - identifier: bilibili
          name: Biligili
          url: https://space.bilibili.com/50378047
          weight: -90
          params:
            icon: bilibili

        # - identifier: twitter
        #   name: Twitter
        #   url: https://twitter.com
        #   params:
        #       icon: brand-twitter

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200


enableGitInfo: true

frontmatter:
    lastmod: ['lastmod', ':git', 'date', 'publishDate']